---
# tasks file for apache

- name: install apache (httpd)
  yum:
    name: httpd
    state: installed
#- name: custom info.php
 # copy:
  #  src: info.php
   # dest: /var/www/html/info.php

- name: enable apache (httpd)
  service:
    name: httpd
    enabled: yes

- name: Reconfgire apache port
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: 
    - Restart Apache



...


