---
# tasks file for mariadb

- name: Install mariadb
  yum:
    name: ['mariadb','mariadb-server']
    state: present

- name: start mariadb
  service:
    name: mariadb
    state: started

- name: Enable mariadb
  service:
    name: mariadb
    enables: yes

...
