---
# tasks file for php

- name: Install PHP
  yum:
    name: ['php','php-mysql']
    state: present

- name: configure info.php
  copy:
    src: info.php
    dest: /var/www/html/info.php
- name: enable apache
  service:
    name: httpd
    enabled: yes

...
  
